#!/usr/bin/env python3
"""Install and register a repository-built GEO expert in local WorkBuddy."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import uuid


EXPERT_NAME = "geo-diagnostic-expert"


def get_module_root() -> Path:
    """Return the repository-owned brand-geo-audit module root."""

    return Path(__file__).resolve().parents[3]


def get_workbuddy_config_dir(explicit_path: Path | None) -> Path:
    """Resolve the local WorkBuddy configuration directory."""

    if explicit_path is not None:
        return explicit_path.expanduser().resolve()
    configured = os.environ.get("WORKBUDDY_CONFIG_DIR", "").strip()
    return Path(configured).expanduser().resolve() if configured else Path.home() / ".workbuddy"


def get_expert_manager_scripts(config_dir: Path) -> Path:
    """Locate WorkBuddy's official expert validation and registration scripts."""

    scripts = (
        config_dir
        / "plugins"
        / "marketplaces"
        / "workbuddy-builtin"
        / "skills"
        / "expert-manager"
        / "scripts"
    )
    required = (scripts / "validate_expert.py", scripts / "register_expert.py")
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise FileNotFoundError("WorkBuddy expert-manager is unavailable: " + ", ".join(missing))
    return scripts


def run_checked(command: list[str]) -> None:
    """Run an official WorkBuddy management command and fail on errors."""

    subprocess.run(command, check=True)


def validate_expert_name(build_dir: Path) -> None:
    """Reject installation targets that are not the expected generated expert."""

    manifest_path = build_dir / ".codebuddy-plugin" / "plugin.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("name") != EXPERT_NAME or build_dir.name != EXPERT_NAME:
        raise ValueError(f"refusing to install unexpected expert directory: {build_dir}")


def install_expert(build_dir: Path, config_dir: Path, session_id: str | None) -> Path:
    """Atomically replace the local expert and restore the previous copy on failure."""

    validate_expert_name(build_dir)
    manager_scripts = get_expert_manager_scripts(config_dir)
    validate_script = manager_scripts / "validate_expert.py"
    register_script = manager_scripts / "register_expert.py"
    plugins_dir = config_dir / "plugins" / "marketplaces" / "my-experts" / "plugins"
    plugins_dir.mkdir(parents=True, exist_ok=True)
    target_dir = plugins_dir / EXPERT_NAME
    unique = uuid.uuid4().hex
    temporary_dir = plugins_dir / f".{EXPERT_NAME}.install-{unique}"
    backup_dir = plugins_dir / f".{EXPERT_NAME}.backup-{unique}"
    shutil.copytree(build_dir, temporary_dir)

    had_previous = target_dir.exists()
    try:
        # WorkBuddy's official validator only accepts experts located under the
        # local my-experts/plugins directory, so validation happens after the
        # repository build has been copied to this temporary installation path
        run_checked([sys.executable, str(validate_script), str(temporary_dir)])
        if had_previous:
            os.replace(target_dir, backup_dir)
        os.replace(temporary_dir, target_dir)
        register_command = [sys.executable, str(register_script), str(target_dir)]
        if session_id:
            register_command.extend(["--session-id", session_id])
        run_checked(register_command)
    except Exception:
        if target_dir.exists():
            shutil.rmtree(target_dir)
        if backup_dir.exists():
            os.replace(backup_dir, target_dir)
        raise
    finally:
        if temporary_dir.exists():
            shutil.rmtree(temporary_dir)
    if backup_dir.exists():
        shutil.rmtree(backup_dir)
    return target_dir


def parse_args() -> argparse.Namespace:
    """Parse local installation CLI arguments."""

    module_root = get_module_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--build-dir",
        type=Path,
        default=module_root / "work" / "mvp-release" / EXPERT_NAME,
        help="Expert directory generated by build_expert.py",
    )
    parser.add_argument(
        "--workbuddy-config-dir",
        type=Path,
        help="Override WORKBUDDY_CONFIG_DIR or ~/.workbuddy",
    )
    parser.add_argument(
        "--session-id",
        default=os.environ.get("CODEBUDDY_SESSION_ID", "").strip() or None,
        help="Optional WorkBuddy session marker",
    )
    return parser.parse_args()


def main() -> int:
    """Install the assembled expert into the local WorkBuddy marketplace."""

    args = parse_args()
    build_dir = args.build_dir.expanduser().resolve()
    if not build_dir.is_dir():
        raise FileNotFoundError(f"build directory does not exist: {build_dir}")
    config_dir = get_workbuddy_config_dir(args.workbuddy_config_dir)
    installed_dir = install_expert(build_dir, config_dir, args.session_id)
    print(f"Installed and registered expert: {installed_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
